### ISSUE TITLE
HTML file lacks info about specific issues?

### ISSUE THREAD

**Issue by stur86** [Filiosoft/npm-audit-html#79]
When I generate the HTML report as specified in the instructions I get to see the number of issues split by severity just fine, but the table below has "0 out of 0" and lists no actual package names for the issues. I'm using Node v14.18.0 and NPM v8.1.0, on Ubuntu. Visualizing the HTML file with Chrome. The information is definitely contained in the JSON file. Is there anything else that I should be wary of, or is this a bug?

**Comment by nprail** [comment]
Are you on the npm-audit-html v2 beta version or are you on v1? v2 is required for NPM v7 and up.

**Comment by stur86** [comment]
I installed it from the package manager, so apparently version is 1.5.0. I assume this means I must get it straight from the repository instead?

**Comment by nprail** [comment]
You can install v2 with `npm install -g npm-audit-html@beta`.

Let me know if you have any issues with it!
