### ISSUE TITLE
The data table is empty

### ISSUE THREAD

**Issue by Tim-Schwalbe** [Filiosoft/npm-audit-html#81]
Hi, somehow the data table is empty since a few days, but it was working before.

I do the following with this docker image: FROM node:lts-bullseye-slim

```
npm i -g npm-audit-html 
npm audit --json | npm-audit-html
```

![image](https://user-images.githubusercontent.com/16404601/139386859-55ff0dbe-a6d8-4a4f-9f2f-53c4a78453de.png)

**Comment by enricoaleandri** [comment]
Breaking Change from report version 1: 
https://github.com/npm/npm-audit-report#break-from-version-1

**Comment by nprail** [comment]
If you are on NPM 7 or higher, you'll need to install `npm-audit-html` from the beta tag like so:

```bash
npm i -g npm-audit-html@beta
```

See #43 for details.
